New upstream version 1.2.0

diff --git a/tools/ods-control.in b/tools/ods-control.in
--- a/tools/ods-control.in
+++ b/tools/ods-control.in
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: ods-control.in 3763 2010-08-20 06:51:46Z rb $
+# $Id: ods-control.in 4135 2010-10-25 10:09:42Z matthijs $
 #
 # Copyright (c) 2009 .SE (The Internet Infrastructure Foundation)
 # All rights reserved.
@@ -31,6 +31,7 @@ progname="ods-control"
 bindir="@OPENDNSSEC_BIN_DIR@"
 sbindir="@OPENDNSSEC_SBIN_DIR@"
 enforcer_pid_file="@OPENDNSSEC_PID_DIR@/enforcerd.pid"
+signer_pid_file="@OPENDNSSEC_PID_DIR@/signerd.pid"
 
 
 case "$1" in
@@ -44,10 +45,34 @@ case "$1" in
 	shift
 	"$bindir/ods-hsmutil" $@
 	;;
-	
+
 'signer')
-	shift
-	"$sbindir/ods-signer" $@
+	case "$2" in
+
+	'start')
+		echo "Starting signer..."
+		"$sbindir/ods-signer" start
+		i=0
+		while [ ! -r "$signer_pid_file" ]; do
+			sleep 1
+			i=$(( $i + 1 ))
+			if [ $i -ge 5 ]; then
+				RETVAL=1
+				echo "Could not start signer"
+				exit $RETVAL
+			fi
+		done
+
+		"$sbindir/ods-signer" running
+		RETVAL=$?
+
+		exit $RETVAL
+		;;
+	*)
+		"$sbindir/ods-signer" $2
+		;;
+
+	esac
 	;;
 
 'enforcer')
@@ -62,8 +87,15 @@ case "$1" in
 			"$sbindir/ods-enforcerd"
 			RETVAL=$?
 			if [ $RETVAL = 0 ]; then
+                i=0
 				while [ ! -r "$enforcer_pid_file" ]; do
 					sleep 1
+                    i=$(( $i + 1 ))
+                    if [ $i -ge 5 ]; then
+                        RETVAL=1
+                        echo "Could not start enforcer"
+                        break
+                    fi
 				done
 			fi
 		fi
@@ -75,9 +107,11 @@ case "$1" in
 		if [ -r "$enforcer_pid_file" ]; then
 			kill -TERM `cat "$enforcer_pid_file"`
 			RETVAL=$?
-			while [ -r "$enforcer_pid_file" ]; do
-				sleep 1
-			done
+			if [ $RETVAL = 0 ]; then
+				while [ -r "$enforcer_pid_file" ]; do
+					sleep 1
+				done
+			fi
 		else
 			echo "Cannot find PID file"
 			RETVAL=1
@@ -105,10 +139,11 @@ case "$1" in
 	;;
 
 'start')
-	echo "Starting signer engine..."
-	"$sbindir/ods-signer" start
-
 	"$0" enforcer start
+
+	echo "Starting signer engine..."
+	"$0" signer start
+
 	;;
 
 'stop')
@@ -117,7 +152,7 @@ case "$1" in
 	echo "Stopping signer engine.."
 	"$sbindir/ods-signer" stop
 	;;
-	
+
 *)
 	echo "usage: $progname ksm|hsm|signer|enforcer|start|stop ..."
 	;;
